<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK8E5ycR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK8E5ycR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerK8E5ycR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerK8E5ycR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerK8E5ycR\App_KernelDevDebugContainer([
    'container.build_hash' => 'K8E5ycR',
    'container.build_id' => '3f07a5e8',
    'container.build_time' => 1606344181,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerK8E5ycR');
