<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFfaHaeJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFfaHaeJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFfaHaeJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFfaHaeJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFfaHaeJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'FfaHaeJ',
    'container.build_id' => '6d63d4af',
    'container.build_time' => 1604610771,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFfaHaeJ');
