<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8SlL3xe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8SlL3xe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8SlL3xe.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8SlL3xe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8SlL3xe\App_KernelDevDebugContainer([
    'container.build_hash' => '8SlL3xe',
    'container.build_id' => '4fc84978',
    'container.build_time' => 1604609633,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8SlL3xe');
