<?php

namespace ContainerNb4PypK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProdRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ProdRepository' shared autowired service.
     *
     * @return \App\Repository\ProdRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ProdRepository'] = new \App\Repository\ProdRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
