<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMRghooF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMRghooF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMRghooF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMRghooF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMRghooF\App_KernelDevDebugContainer([
    'container.build_hash' => 'MRghooF',
    'container.build_id' => '3f0cd162',
    'container.build_time' => 1605136627,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMRghooF');
