<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJA6oiZU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJA6oiZU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJA6oiZU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJA6oiZU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJA6oiZU\App_KernelDevDebugContainer([
    'container.build_hash' => 'JA6oiZU',
    'container.build_id' => '1d1f8e9b',
    'container.build_time' => 1605046834,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJA6oiZU');
